### ISSUE TITLE
yarll.misc.exceptions.ClassNotRegisteredError

### ISSUE THREAD

**Issue by Blankslide** [arnomoonens/DeepRL#11]
@arnomoonens 
Hi,

I tried running the CartPole-v0-FittedQ-experiment, but I got the error below. Could you please take a look at it? Thank you!

I observed that the `register_agent ` is not called from the main file. 

yarll.misc.exceptions.ClassNotRegisteredError: The agent FittedQIteration for state dimensionality continuous, action space discrete and RNN=False is not registered.

**Comment by arnomoonens** [comment]
Hello,

Thank you for the interest in my code!

Could you tell me how you installed the code and how you ran the experiment?
For me it worked using the latest revision on the `tf2` branch by running `python yarll/main.py experiment_specs/CartPole-v0-FittedQ-experiment.json`.

Note that the version that is installed using _pip_ is quite outdated by now. In case you installed it that way, it is best to clone the repository instead, such that you have the latest version. Also see the [README](https://github.com/arnomoonens/yarll#how-to-run) on how to use the code that way.

**Comment by Blankslide** [comment]
@arnomoonens 

Thank you for your prompt response and for providing this awesome repository. I try to follow your suggestion by installing the cloned version instead. I installed it via **pip git+**. I have also gone through the README as suggested.

Moreover, after running `python yarll/main.py experiment_specs/CartPole-v0-FittedQ-experiment.json`, it seems it hanged at : I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:176] None of the MLIR Optimization Passes are enabled (registered 2). 

Am I to run  ` python -m yarll.misc.plot_statistics <path_to_stats>`  as the next step?

I anticipate your response.

**Comment by Blankslide** [comment]
Update:

So I waited for the experiment to finish running after which I then run `python -m yarll.misc.plot_statistics C:\tmp\CartPole-v0-FittedQ`, but I got the error below:

line 130, in tf_scalar_data
    task = int(pattern.search(run).group(1))
AttributeError: 'NoneType' object has no attribute 'group'

**Comment by arnomoonens** [comment]
Hello,

There is currently a bug in the `plot_statistics` file. I suggest to look at statistics using Tensorboard (installed together with TensorFlow). You can run it using `tensorboard --logdir C:\tmp\CartPole-v0-FittedQ`. You can also run this while the experiment is still running to see if the algorithm is learning well.

**Comment by Blankslide** [comment]
> Hello,
> 
> There is currently a bug in the `plot_statistics` file. I suggest to look at statistics using Tensorboard (installed together with TensorFlow). You can run it using `tensorboard --logdir C:\tmp\CartPole-v0-FittedQ`. You can also run this while the experiment is still running to see if the algorithm is learning well.

 I will. Thank you!
